<!DOCTYPE html>
<html>
<title>Tabbed Panels</title>
<style >
body {
      font-family: Arial, Helvetica, sans-serif;
      color: #222;
  }
.tab-bar {
      list-style: none;
      margin: 0;
      padding: 10px 10px 0 10px;
      background: #7BBBED;
      overflow: hidden;
  }
.tab-bar li {
      padding: 8px 20px;
      float: left;
      margin-right: 8px;
      background: #fff;
      cursor: pointer;
  }
.panel {
      min-height: 200px;
      border: 1px solid #1FEFE5;
      border-top: 0 none;
      padding: 15px;
}
#tab-2 {
      background: #1FEFE5;
}
  #panel-2 {
      display: none;
  }
.paging-nav {
  text-align: right;
  padding-top: 2px;
}
.paging-nav a {
  margin: auto 1px;
  text-decoration: none;
  display: inline-block;
  padding: 1px 7px;
  background: #91b9e6;
  color: white;
  border-radius: 3px;
}
 .paging-nav .selected-page {
  background: #187ed5;
  font-weight: bold;
}
.paging-nav,
  #tableData {
  width: 1000px;
  margin: 0 auto;
  font-family: Arial, sans-serif;
}
.paging-nav,
 #tableData2 {
  width: 1000px;
  margin: 0 auto;
  font-family: Arial, sans-serif;
}
p{
  margin-left: 938px;
}
h2{
  margin-right:780px;
  float: right;
}
.nav > li > a {
  font-size: 15px;
}
</style>
<?php 
use Zend\Session\Container; 
$session = new Container('user');
      $uid = $session->id;
      $auth= $session->auth;
?>
<head style="padding:3px; margin:0px; background-color:#fff;font-family:'Open Sans',sans-serif,arial,helvetica,verdana">
<script src="js/jssor.slider-22.0.7.min.js" type="text/javascript" data-library="jssor.slider" data-version="22.0.7"></script>
<script type="text/javascript">
jssor_1_slider_init = function() {

            var jssor_1_SlideoTransitions = [
              [{b:-1,d:1,o:-1},{b:0,d:1000,x:-257,y:-5,o:1}],
              [{b:480,d:520,x:120,y:-270}],
              [{b:1000,d:500,y:250},{b:8000,d:1000,x:600}],
              [{b:-1,d:1,o:-1,sX:-0.6,sY:-0.6},{b:1500,d:500,o:1,r:360,sX:0.6,sY:0.6},{b:8000,d:1000,y:-150}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:2000,d:1000,o:1,tZ:200},{b:3000,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:3000,d:1000,o:1,tZ:200},{b:4000,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:4000,d:1000,o:1,tZ:200},{b:5000,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:5000,d:1000,o:1,tZ:200},{b:6000,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:6000,d:1000,o:1,tZ:200},{b:7000,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,o:-1,tZ:-200},{b:7000,d:1000,o:1,tZ:200},{b:8000,d:1000,o:-1,tZ:200}],
              [{b:-1,d:1,c:{x:250.0,t:-250.0}},{b:0,d:1000,c:{x:-250.0,t:250.0}},{b:5000,d:1000,y:100}],
              [{b:-1,d:1,o:-1},{b:1000,d:1000,o:1},{b:5000,d:1000,y:280}],
              [{b:2000,d:1000,y:190,e:{y:28}},{b:5000,d:1000,x:280}],
              [{b:3000,d:520,y:50},{b:5000,d:1000,y:-50}],
              [{b:3520,d:480,x:-400},{b:5000,d:800,x:400,e:{x:7}}],
              [{b:4000,d:500,x:-400},{b:5000,d:800,x:400,e:{x:7}}],
              [{b:4500,d:500,x:-400},{b:5000,d:800,x:400,e:{x:7}}],
              [{b:-1,d:1,c:{x:250.0,t:-250.0}},{b:0,d:1000,c:{x:-250.0,t:250.0}},{b:10000,d:500,y:90}],
              [{b:-1,d:1,c:{x:150.0,t:-150.0}},{b:1000,d:1000,c:{x:-150.0,t:150.0}},{b:10000,d:500,c:{y:150.0,m:-150.0}}],
              [{b:2000,d:500,x:220}],
              [{b:3500,d:500,rX:-20},{b:4000,d:1000,rX:40},{b:5000,d:500,rX:-10},{b:9500,d:500,o:-1}],
              [{b:3500,d:2000,r:360}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,x:76,y:-25,o:1}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,x:47,y:65,o:1}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,x:-47,y:65,o:1}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,x:-76,y:-25,o:1}],
              [{b:-1,d:1,o:-1},{b:2500,d:500,y:-80,o:1}],
              [{b:-1,d:1,c:{x:120.0,t:-120.0}},{b:6100,d:400,c:{x:-120.0,t:120.0}},{b:10000,d:500,y:-120}],
              [{b:6500,d:500,x:220}],
              [{b:-1,d:1,o:-1,r:180,sX:-0.5,sY:-0.5},{b:7000,d:500,o:1,r:180,sX:0.5,sY:0.5},{b:8000,d:500,o:-1,r:180,sX:9,sY:9}],
              [{b:-1,d:1,o:-1,r:180,sX:-0.5,sY:-0.5},{b:8000,d:500,o:1,r:180,sX:0.5,sY:0.5},{b:9000,d:500,o:-1,r:180,sX:9,sY:9}],
              [{b:-1,d:1,o:-1,r:180,sX:-0.5,sY:-0.5},{b:9000,d:500,o:1,r:180,sX:0.5,sY:0.5},{b:9500,d:500,o:-1,r:180,sX:9,sY:9}]
            ];

            var jssor_1_options = {
              $AutoPlay: true,
              $SlideEasing: $Jease$.$InOutSine,
              $CaptionSliderOptions: {
                $Class: $JssorCaptionSlideo$,
                $Transitions: jssor_1_SlideoTransitions,
                $Breaks: [
                  [{d:3000,b:8000,t:2}],
                  [{d:2000,b:5000}],
                  [{d:3000,b:9500,t:2}]
                ]
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
              }
            };

            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 980);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $Jssor$.$AddEvent(window, "load", ScaleSlider);
            $Jssor$.$AddEvent(window, "resize", ScaleSlider);
            $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
};
</script>
<style>
        .jssorb05 {
            position: absolute;
        }
        .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
            position: absolute;
            width: 16px;
            height: 16px;
            background: url('img/b05.png') no-repeat;
            overflow: hidden;
            cursor: pointer;
        }
        .jssorb05 div { background-position: -7px -7px; }
        .jssorb05 div:hover, .jssorb05 .av:hover { background-position: -37px -7px; }
        .jssorb05 .av { background-position: -67px -7px; }
        .jssorb05 .dn, .jssorb05 .dn:hover { background-position: -97px -7px; }

       
        .jssora22l, .jssora22r {
            display: block;
            position: absolute;
            width: 40px;
            height: 58px;
            cursor: pointer;
            background: url('img/a22.png') center center no-repeat;
            overflow: hidden;
        }
        .jssora22l { background-position: -10px -31px; }
        .jssora22r { background-position: -70px -31px; }
        .jssora22l:hover { background-position: -130px -31px; }
        .jssora22r:hover { background-position: -190px -31px; }
        .jssora22l.jssora22ldn { background-position: -250px -31px; }
        .jssora22r.jssora22rdn { background-position: -310px -31px; }
        .jssora22l.jssora22lds { background-position: -10px -31px; opacity: .3; pointer-events: none; }
        .jssora22r.jssora22rds { background-position: -70px -31px; opacity: .3; pointer-events: none; }
</style>
<p style="margin-top: 3px; ">
            <?php if($uid==null) {?>
              <a href="<?= $this->url('onlineproperty', ['action' => 'login']) ?>"><img src="<?= $this->basePath('img/login.png') ?>" onmouseover="src='<?= $this->basePath('img/login2.png') ?>';"onmouseout="   src='<?= $this->basePath('img/login.png') ?>';" height="37"></a>

              <a href="<?= $this->url('onlineproperty', ['action' => 'register']) ?>"><img src="<?= $this->basePath('img/register1.png') ?>" onmouseover="src='<?= $this->basePath('img/register2.png') ?>';"onmouseout="src='<?= $this->basePath('img/register1.png') ?>';" height="37"></a>

            <?php }else{ ?>
            <a href="<?= $this->url('onlineproperty', ['action' => 'logout']) ?>"><img src="<?= $this->basePath('img/logout1.png') ?>" onmouseover="src='<?= $this->basePath('img/logout2.png') ?>';"onmouseout="src='<?= $this->basePath('img/logout1.png') ?>';" height="37"></a>
            <?php } ?>
            <?php if($auth=="1"){?>
              <a href="<?= $this->url('postmng', ['action' => 'index']) ?>"><img src="<?= $this->basePath('img/profile1.png') ?>" onmouseover="src='<?= $this->basePath('img/profile2.png') ?>';"onmouseout="src='<?= $this->basePath('img/profile1.png') ?>';" height="37"></a>
            <?php }elseif($auth=="2") {?>
              <a href="<?= $this->url('userprofile', ['action' => 'index']) ?>"><img src="<?= $this->basePath('img/profile1.png') ?>" onmouseover="src='<?= $this->basePath('img/profile2.png') ?>';"onmouseout="src='<?= $this->basePath('img/profile1.png') ?>';" height="37"></a>
            <?php }?> 
</p>
<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 980px; height: 380px; overflow: hidden; visibility: hidden;">
        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">

            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>

        </div>

        <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 980px; height: 380px; overflow: hidden;">

            <div data-b="0" data-p="170.00" data-po="80% 55%">
                <img data-u="image" src="img/01.jpg" />
                <div data-u="caption" data-t="0" style="position:absolute;top:25px;left:277px;width:500px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">Welcome To Our Online Property ! !</div>

                <div data-u="caption" data-t="1" style="position:absolute;top:600px;left:-100px;width:330px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">Operating Partners Myanmar...</div>
                
                <div data-u="caption" data-t="4" data-3d="1" style="position:absolute;top:200px;left:550px;width:200px;height:100px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:24px;color:#ffffff;line-height:100px;text-align:center;">Condo</div>

                <div data-u="caption" data-t="5" data-3d="1" style="position:absolute;top:200px;left:550px;width:200px;height:100px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:24px;color:#ffffff;line-height:100px;text-align:center;">Apartment</div>

                <div data-u="caption" data-t="6" data-3d="1" style="position:absolute;top:200px;left:550px;width:200px;height:100px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:24px;color:#ffffff;line-height:100px;text-align:center;">House</div>

                <div data-u="caption" data-t="7" data-3d="1" style="position:absolute;top:200px;left:550px;width:200px;height:100px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:24px;color:#ffffff;line-height:100px;text-align:center;">Land</div>

                <div data-u="caption" data-t="8" data-3d="1" style="position:absolute;top:200px;left:550px;width:200px;height:100px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:24px;color:#ffffff;line-height:100px;text-align:center;">Factory</div>

                <div data-u="caption" data-t="9" data-3d="1" style="position:absolute;top:200px;left:550px;width:200px;height:100px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:24px;color:#ffffff;line-height:100px;text-align:center;">Office</div>

            </div>

            <div data-b="1" data-p="170.00" style="display:none;">
                <img data-u="image" src="img/02.jpg" />
                
                <div data-u="caption" data-t="12" style="position:absolute;top:-100px;left:720px;width:160px;height:90px;z-index:0;background-color:rgba(235,81,0,0.7);font-size:20px;color:#ffffff;line-height:90px;text-align:center;">Location</div>
                <div style="position:absolute;top:40px;left:300px;width:400px;height:200px;z-index:0; overflow:hidden;">
                   
                <div data-u="caption" data-t="14" style="position:absolute;top:50px;left:400px;width:450px;height:30px;z-index:0;font-size:18px;color:#ffffff;line-height:30px;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Yangon </div>

                <div data-u="caption" data-t="15" style="position:absolute;top:100px;left:400px;width:450px;height:30px;z-index:0;font-size:18px;color:#ffffff;line-height:30px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Mandalay</div>
                   
                </div>
               
            </div>
            <a data-u="any" href="http://www.jssor.com" style="display:none">Introduction Slider</a>

            <div data-b="2" data-p="170.00" style="display:none;">

                <img data-u="image" src="img/04.jpg" />
                <div data-u="caption" data-t="17" style="position:absolute;top:310px;left:50px;width:500px;height:30px;z-index:0;background-color:rgba(235,81,0,0.5);font-size:20px;color:#ffffff;line-height:30px;text-align:center;">Operating Partners Myanmar ! !</div>

                <div data-u="caption" data-t="20" data-3d="1" style="position:absolute;top:140px;left:690px;width:200px;height:200px;z-index:0;">
                    <div data-u="caption" data-t="21" style="position:absolute;top:0px;left:0px;width:200px;height:200px;z-index:0;">
                        <img data-u="caption" data-t="22" style="position:absolute;top:85px;left:85px;width:30px;height:30px;z-index:0;" src="img/icon_opera.png" />
                        <img data-u="caption" data-t="23" style="position:absolute;top:85px;left:85px;width:30px;height:30px;z-index:0;" src="img/icon_safari.png" />
                        <img data-u="caption" data-t="24" style="position:absolute;top:85px;left:85px;width:30px;height:30px;z-index:0;" src="img/icon_ie.png" />
                        <img data-u="caption" data-t="25" style="position:absolute;top:85px;left:85px;width:30px;height:30px;z-index:0;" src="img/icon_firefox.png" />
                        <img data-u="caption" data-t="26" style="position:absolute;top:85px;left:85px;width:30px;height:30px;z-index:0;" src="img/icon_chrome.png" />

                    </div>
                </div>

                <div data-u="caption" data-t="27" style="position:absolute;top:20px;left:20px;width:240px;height:80px;z-index:0;background-color:rgba(0,0,124,0.3); overflow:hidden;">
                    <div style="position:absolute;top:0px;left:20px;width:200px;height:50px;z-index:0;font-size:24px;color:#ffffff;line-height:50px;">Location

                    </div>
                </div>

                <div data-u="caption" data-t="29" style="position:absolute;top:150px;left:250px;width:200px;height:100px;z-index:0;background-color:rgba(235,81,0,0.7);font-size:24px;color:#ffffff;line-height:100px;text-align:center;">Yangon</div>

                <div data-u="caption" data-t="31" style="position:absolute;top:150px;left:250px;width:200px;height:100px;z-index:0;background-color:rgba(235,81,0,0.7);font-size:24px;color:#ffffff;line-height:100px;text-align:center;">Mandalay</div>
            </div>
        </div>
        
        <div data-u="navigator" class="jssorb05" style="bottom:16px;right:16px;" data-autocenter="1">
            <div data-u="prototype" style="width:16px;height:16px;"></div>
        </div>
        <span data-u="arrowleft" class="jssora22l" style="top:0px;left:10px;width:40px;height:58px;" data-autocenter="2"></span>
        <span data-u="arrowright" class="jssora22r" style="top:0px;right:10px;width:40px;height:58px;" data-autocenter="2"></span>
</div>
    <script type="text/javascript">jssor_1_slider_init();</script>
    
    </head>
</br>
<body background="../public/img/cover5.jpg">
       
         <ul class="tab-bar">
              <li id="tab-1" onclick="switchOne()">For Sale</li>
              <li id="tab-2" onclick="switchTwo()">For Rent</li>
         </ul>

<div class="panel" id="panel-1" >
<div class="tab-details"style="display: block;">

<form class="form" method="post" id="form-propertysearch">

<div>
  <select type="text" name="type" value="" placeholder="type" style="color: #bd726c; width: 200px; border-radius: 5px; height: 31px;  box-shadow: none; border: 1px solid #b6b5b5;">
    <option value="">--Type--</option>
    <option value="Condo">Condo</option>
    <option value="Apartment">Apartment</option>
    <option value="Land">Land</option>
    <option value="Factory">Factory</option>
    <option value="House">House</option>
    <option value="Office">Office</option>
  </select>
  
  <select type="text" name="location" value="" placeholder="Loation" style="color: #bd726c; width: 200px; border-radius: 5px; height: 31px;  box-shadow: none; border: 1px solid #b6b5b5;">
    <option value="">--Location--</option>
    <option value="yangon">Yangon</option>
    <option value="mandalay">Mandalay </option>
  </select>
</div>
<br>

  <select type="text" name="price1" value="" placeholder="Price" style="color: #bd726c; width: 200px; border-radius: 5px; height: 31px;  box-shadow: none; border: 1px solid #b6b5b5;">
    <option value="">--Max Price--</option>
    <option value="1000000">10 lakhs</option>
    <option value="10000000">100 lakhs</option>
    <option value="100000000">1000 lakhs</option>
    <option value="1000000000">10000 lakhs</option>
    <option value="10000000000">100000 lakhs</option>
  </select>
  <select type="text" name="price2" value="" placeholder="Price" style="color: #bd726c; width: 200px; border-radius: 5px; height: 31px;  box-shadow: none; border: 1px solid #b6b5b5;">
    <option value="">--Min Price--</option>
    <option value="1000000">10 lakhs</option>
    <option value="10000000">100 lakhs</option>
    <option value="100000000">1000 lakhs</option>
    <option value="10000000000">10000 lakhs</option> 
  </select>
<br>
<div style=" position: relative; margin-top: 10px; width: 96.5%; margin-left: 200px; margin-bottom: 5px; position: relative; width: 96.5%;">
  <input type="submit" name="search" id="search" value="Search" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >
</div>
</form>
 <hr>
 </div>
     <table id="tableData" class="table table-bordered table-striped" border="1" class="forsale">
    <tr>
      <th width="317" align="left">TypeName</th>
      <th width="317" align="left">Price</th>
      <th width="317" align="left">Location</th>
      <th width="317" align="left">Contact Phone</th>
      <th width="317" align="left">Address</th>
      <th width="317" align="left"></th>
    </tr> 
                                        
    <tr>
      <?php
      $foralert=0; 
      foreach($sale as $sales) : ?>
           <?php $type=$sales->type_name;
                $location=$sales->location;
                $price=$sales->price; ?>
                  <?php   if (isset($_POST['search'])) {
                  $price1=$_POST['price1'];
                  $price2=$_POST['price2']; 
                    if($_POST['type']!=null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']!=null) {
                       if($sales->type_name==$_POST['type'] AND $sales->location==$_POST['location'] AND  $price>=$price2 && $price <=$price1) {
                          $price=$sales->price;
                  ?>
         <tr>
           <td>
                <?= $sales->type_name ?>
           </td>
           <td>
                 <?php echo number_format("$price");?> 
           </td>
           <td>
                <?= $sales->location ?>
           </td>
           <td>
                <?= $sales->contact_phnumber ?>
           </td>
           <td>
                <?= $sales->contact_address ?>
           </td>
           <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail','id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
           </td>
     
         </tr>

<?php
        } 

        }elseif($_POST['type']==null AND $_POST['location']==null AND $_POST['price1']==null AND $_POST['price2']==null){
           $price=$sales->price;
          ?>
           
      <tr>
         <td>
              <?= $sales->type_name ?>
         </td>
         <td>
              <?php echo number_format("$price");?> 
         </td>
         <td>
              <?= $sales->location ?>
         </td>
         <td>
              <?= $sales->contact_phnumber ?>
         </td>
         <td>
              <?= $sales->contact_address ?>
         </td>
         <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
     </tr>

         <?php }elseif($_POST['type']!=null AND $_POST['location']==null AND $_POST['price1']==null AND $_POST['price2']==null){
            if($sales->type_name==$_POST['type']) {
              $price=$sales->price;
            ?> 
        <tr>
           <td>
                <?= $sales->type_name ?>
           </td>
           <td>
                 <?php echo number_format("$price");?> 
           </td>
           <td>
                <?= $sales->location ?>
           </td>
           <td>
                <?= $sales->contact_phnumber ?>
           </td>
           <td>
                <?= $sales->contact_address ?>
           </td>
           <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
          </td>
     
        </tr>
         <?php } } 
elseif($_POST['type']!=null AND $_POST['location']==null AND $_POST['price1']==null AND $_POST['price2']!=null){
            if($sales->type_name==$_POST['type'] &&  $price >=$price2) {
              $price=$sales->price;
            ?> 
        <tr>
           <td>
                <?= $sales->type_name ?>
           </td>
           <td>
                 <?php echo number_format("$price");?> 
           </td>
           <td>
                <?= $sales->location ?>
           </td>
           <td>
                <?= $sales->contact_phnumber ?>
           </td>
           <td>
                <?= $sales->contact_address ?>
           </td>
           <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
           </td>
       </tr>
         <?php } }
         elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']==null AND $_POST['price2']!=null){
            if($sales->location==$_POST['location'] &&  $price >=$price2) {
              $price=$sales->price;
            ?> 
        <tr>
           <td>
                <?= $sales->type_name ?>
           </td>
           <td>
                 <?php echo number_format("$price");?> 
           </td>
           <td>
                <?= $sales->location ?>
           </td>
           <td>
                <?= $sales->contact_phnumber ?>
           </td>
           <td>
                <?= $sales->contact_address ?>
           </td>
           <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
           </td>
        </tr>
         <?php } }
          elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']==null){
            if($sales->location==$_POST['location'] &&  $price <=$price1) {
              $price=$sales->price;
            ?> 
        <tr>
           <td>
                <?= $sales->type_name ?>
           </td>
           <td>
                 <?php echo number_format("$price");?> 
           </td>
           <td>
                <?= $sales->location ?>
           </td>
           <td>
                <?= $sales->contact_phnumber ?>
           </td>
           <td>
                <?= $sales->contact_address ?>
           </td>
          <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
           </td>
        </tr>
         <?php } }
          elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']!=null){
            $price1=$_POST['price1'];
        $price2=$_POST['price2'];
        if ($sales->location==$_POST['location'] && $price1 < $price2) {
            $foralert=1;
        }
            elseif($sales->location==$_POST['location'] &&  $price>=$price2 && $price <=$price1 ) {
              $price=$sales->price;
            ?> 
        <tr>
           <td>
                <?= $sales->type_name ?>
           </td>
           <td>
                 <?php echo number_format("$price");?> 
           </td>
           <td>
                <?= $sales->location ?>
           </td>
           <td>
                <?= $sales->contact_phnumber ?>
           </td>
           <td>
                <?= $sales->contact_address ?>
           </td>
           <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
           </td>
       </tr>
         <?php } }
         elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']==null AND $_POST['price2']==null){
                if( $sales->location==$_POST['location']){
                  $price=$sales->price;
            ?>
            <tr>
                <td>
                    <?= $sales->type_name ?>
               </td>
               <td>
                    <?php echo number_format("$price");?> 
               </td>
               <td>
                    <?= $sales->location ?>
               </td>
               <td>
                    <?= $sales->contact_phnumber ?>
               </td>
               <td>
                    <?= $sales->contact_address ?>
               </td>
               <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
               </td>
            </tr>
        <?php }

      } elseif($_POST['type']==null AND $_POST['location']==null AND $_POST['price1']!=null AND $_POST['price2']!=null){
        $price1=$_POST['price1'];
        $price2=$_POST['price2'];
        if ($price1 < $price2) {
            $foralert=1;
        }
             elseif( $price>=$price2 && $price <=$price1){
              $price=$sales->price;
         ?>
          <tr>
              <td>
                  <?= $sales->type_name ?>
             </td>
             <td>
                   <?php echo number_format("$price");?> 
             </td>
             <td>
                  <?= $sales->location ?>
             </td>
             <td>
                  <?= $sales->contact_phnumber ?>
             </td>
             <td>
                  <?= $sales->contact_address ?>
             </td>
             <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
             </td>
        </tr>
        <?php }
      }
      elseif($_POST['type']==null AND $_POST['location']==null AND $_POST['price1']!=null AND $_POST['price2']==null){
             if( $price <=$price1 ){
              $price=$sales->price;
         ?>
          <tr>
              <td>
                  <?= $sales->type_name ?>
             </td>
             <td>
                   <?php echo number_format("$price");?>  
             </td>
             <td>
                  <?= $sales->location ?>
             </td>
             <td>
                  <?= $sales->contact_phnumber ?>
             </td>
             <td>
                  <?= $sales->contact_address ?>
             </td>
             <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
             </td>
         </tr>
        <?php }
      }
      elseif($_POST['type']==null AND $_POST['location']==null AND $_POST['price1']==null AND $_POST['price2']!=null){
        $price=$sales->price;
             if( $price >=$price2 ){
              $price=$sales->price;
         ?>
          <tr>
             <td>
                  <?= $sales->type_name ?>
             </td>
             <td>
                 <?php echo number_format("$price");?> 
             </td>
             <td>
                  <?= $sales->location ?>
             </td>
             <td>
                  <?= $sales->contact_phnumber ?>
             </td>
             <td>
                  <?= $sales->contact_address ?>
             </td>
             <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
             </td>
         </tr>
        <?php }
      }
      elseif($_POST['type']!=null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']==null){
        $price=$sales->price;
             if( $price <=$price1 ){
              $price=$sales->price;
         ?>
          <tr>
             <td>
                  <?= $sales->type_name ?>
             </td>
             <td>
                 <?php echo number_format("$price");?> 
             </td>
             <td>
                  <?= $sales->location ?>
             </td>
             <td>
                  <?= $sales->contact_phnumber ?>
             </td>
             <td>
                  <?= $sales->contact_address ?>
             </td>
            <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
            </td>
         </tr>
        <?php }
      }
      elseif($_POST['type']!=null AND $_POST['location']!=null AND $_POST['price1']==null AND $_POST['price2']!=null){
        $price=$sales->price;
        if( $sales->location==$_POST['location']){
             if( $price >=$price2 ){
              $price=$sales->price;
         ?>
          <tr>
             <td>
                  <?= $sales->type_name ?>
             </td>
             <td>
                 <?php echo number_format("$price");?> 
             </td>
             <td>
                  <?= $sales->location ?>
             </td>
             <td>
                  <?= $sales->contact_phnumber ?>
             </td>
             <td>
                  <?= $sales->contact_address ?>
             </td>
             <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
           </td>
         </tr>
        <?php }
      }
    }
      elseif($_POST['type']!=null AND $_POST['location']!=null AND $_POST['price1']==null AND $_POST['price2']==null)
          { 
             if($sales->type_name==$_POST['type'] AND $sales->location==$_POST['location'] ){
              $price=$sales->price;
        ?>
        <tr>
            <td>
                <?= $sales->type_name ?>
           </td>
           <td>
                <?php echo number_format("$price");?> 
           </td>
           <td>
                <?= $sales->location ?>
           </td>
           <td>
                <?= $sales->contact_phnumber ?>
           </td>
           <td>
                <?= $sales->contact_address ?>
           </td>
           <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
           </td>
      </tr>
       <?php }
       
     }elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']!=null){
            if($sales->location==$_POST['location'] AND  $price<=$_POST['price1'] && $price >=$_POST['price2']){
              $price=$sales->price;
        ?>
        <tr>
          <td>
              <?= $sales->type_name ?>
         </td>
         <td>
              <?php echo number_format("$price");?> 

         </td>
         <td>
              <?= $sales->location ?>
         </td>
         <td>
              <?= $sales->contact_phnumber ?>
         </td>
         <td>
              <?= $sales->contact_address ?>
         </td>
         <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
      <?php }

    }elseif($_POST['type']!=null AND $_POST['location']==null AND $_POST['price1']!=null AND $_POST['price1']!=null){
        $price1=$_POST['price1'];
        $price2=$_POST['price2'];
        if ($sales->type_name==$_POST['type'] && $price1 < $price2) {
            $foralert=1;
        }
           elseif($sales->type_name==$_POST['type'] AND $price>=$price2 && $price <=$price1 ){
            $price=$sales->price;
        ?>
       <tr>
          <td>
              <?= $sales->type_name ?>
         </td>
         <td>
              <?php echo number_format("$price");?> 
         </td>
         <td>
              <?= $sales->location ?>
         </td>
         <td>
              <?= $sales->contact_phnumber ?>
         </td>
         <td>
              <?= $sales->contact_address ?>
         </td>
         <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
         </td>
     </tr>
     <?php }
     }}else { 
         
      ?>

      <tr>
          <td>
              <?= $sales->type_name ?>
         </td>
         <td>
             <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $sales->location ?>
         </td>
         <td>
              <?= $sales->contact_phnumber ?>
         </td>
         <td>
              <?= $sales->contact_address ?>
         </td>
         <td>
                <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $sales->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
         </td>
    </tr>

 <?php        }
endforeach; 
?>
</table>
   </div>
   <?php 
   if($foralert=="1"){?>
    <script type="text/javascript">
    alert("Maximun Price can't greater than Minimun Price!!");
    </script>
   <?php } ?>

   <div class="panel" id="panel-2">
   <div class="search">
   <style>

   </style>
<form class="form" method="post">
<div>
  <select type="text" name="type" value="" placeholder="type" style="color: #bd726c; width: 200px; border-radius: 5px; height: 31px;  box-shadow: none; border: 1px solid #b6b5b5;">
    <option value="">--Type--</option>
    <option value="Condo">Condo</option>
    <option value="Apartment">Apartment</option>
    <option value="Land">Land</option>
    <option value="Factory">Factory</option>
    <option value="House">House</option>
    <option value="Office">Office</option>
  </select>
  
  <select type="text" name="location" value="" placeholder="Loation" style="color: #bd726c; width: 200px; border-radius: 5px; height: 31px;  box-shadow: none; border: 1px solid #b6b5b5;">
    <option value="">--Location--</option>
    <option value="yangon">Yangon</option>
    <option value="mandalay">Mandalay </option>
  </select>
</div>
<br>

  <select type="text" name="price1" value="" placeholder="Price" style="color: #bd726c; width: 200px; border-radius: 5px; height: 31px;  box-shadow: none; border: 1px solid #b6b5b5;">
    <option value="">--Max Price--</option>
    <option value="100000">1 lakhs</option>
    <option value="500000">5 lakhs</option>
    <option value="1000000">10 lakhs</option>
    <option value="2000000">20 lakhs</option>
    <option value="1000000000">10000 lakhs</option>
  </select>


  <select type="text" name="price2" value="" placeholder="Price" style="color: #bd726c; width: 200px; border-radius: 5px; height: 31px;  box-shadow: none; border: 1px solid #b6b5b5;">
    <option value="">--Min Price--</option>
    <option value="100000">1 lakhs</option>
    <option value="500000">5 lakhs</option>
    <option value="1000000">10 lakhs</option>
    <option value="10000000">100 lakhs</option> 
  </select>
<br>

<div style=" position: relative; margin-top: 10px; width: 96.5%; margin-left: 200px; margin-bottom: 5px; position: relative; width: 96.5%;">
  <input type="submit" name="search2" id="search2" value="Search" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >
</div>
</form>
<hr/>
</div>
     <table id="tableData2" class="table table-bordered table-striped" border="1" class="forrent">
      <tr>
        <th width="317" align="left">TypeName</th>
        <th width="317" align="left">Price</th>
        <th width="317" align="left">Location</th>
        <th width="317" align="left">Contact Phone</th>
        <th width="317" align="left">Address</th>
        <th width="317" align="left"></th>
     </tr> 
                                        
     <tr>
     <?php
     $foralert=0; 
     foreach($rent as $rents) : ?>
      <?php $type=$rents->type_name;
            $location=$rents->location;
            $price=$rents->price; ?>
             <?php   if (isset($_POST['search2'])) {
             $price1=$_POST['price1'];
             $price2=$_POST['price2']; 
              if($_POST['type']!=null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']!=null) {
                 if($rents->type_name==$_POST['type'] AND $rents->location==$_POST['location'] AND $price>=$price2 && $price <=$price1) {
                   $price=$rents->price;
             ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
          </td>
          <td>
             <?php  echo number_format("$price");?> 
          </td>
          <td>
              <?= $rents->location ?>
          </td>
          <td>
              <?= $rents->contact_phnumber ?>
          </td>
          <td>
              <?= $rents->contact_address ?>
          </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
         </td>
      </tr>

<?php
  } 
        }elseif($_POST['type']==null AND $_POST['location']==null AND $_POST['price1']==null AND $_POST['price2']==null){
           $price=$rents->price;
          ?>
         
      <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>

         <?php }elseif($_POST['type']!=null AND $_POST['location']==null AND $_POST['price1']==null AND $_POST['price2']==null){
            if($rents->type_name==$_POST['type']) {
              $price=$rents->price;
            ?> 
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
       </tr>
         <?php } } elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']==null AND $_POST['price2']==null){
                if($rents->location==$_POST['location'] ){
                  $price=$rents->price;
            ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
            <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }} elseif($_POST['type']==null AND $_POST['location']==null AND $_POST['price1']!=null AND $_POST['price2']==null){
             if( $price <=$price1 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
             <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }
      }
      elseif($_POST['type']==null AND $_POST['location']==null AND $_POST['price1']==null AND $_POST['price2']!=null){
             if( $price >=$price2 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
       </tr>
        <?php }
      }
      elseif($_POST['type']==null AND $_POST['location']==null AND $_POST['price1']!=null AND $_POST['price2']!=null){
        $price1=$_POST['price1'];
        $price2=$_POST['price2'];
        if ($price1 < $price2) {
            $foralert=1;
        }
             elseif($price>=$price2 && $price <=$price1 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
            <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }
      }
      elseif($_POST['type']!=null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']==null){
             if( $rents->type_name==$_POST['type'] && $rents->location==$_POST['location'] && $price <=$price1 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }
      }
      elseif($_POST['type']!=null AND $_POST['location']!=null AND $_POST['price1']==null AND $_POST['price2']!=null){
             if( $rents->type_name==$_POST['type'] && $rents->location==$_POST['location'] && $price >=$price2 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }
      }
      elseif($_POST['type']!=null AND $_POST['location']==null AND $_POST['price1']==null AND $_POST['price2']!=null){
             if( $rents->type_name==$_POST['type'] && $price >=$price2 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }
      }
      elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']==null AND $_POST['price2']!=null){
             if( $rents->location==$_POST['location'] && $price >=$price2 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }
      }
      elseif($_POST['type']!=null AND $_POST['location']==null AND $_POST['price1']!=null AND $_POST['price2']==null){
             if( $rents->type_name==$_POST['type'] && $price <=$price1 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }
      }
      elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']==null){
             if( $rents->location==$_POST['location'] && $price <=$price1 ){
              $price=$rents->price;
         ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
              <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
        <?php }
      } 
      elseif($_POST['type']!=null AND $_POST['location']!=null AND $_POST['price1']==null AND $_POST['price2']==null)
          { 
            if($rents->type_name==$_POST['type'] AND $rents->location==$_POST['location'] ){
              $price=$rents->price;
              ?>
            
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
             <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
       <?php } 
     }elseif($_POST['type']==null AND $_POST['location']!=null AND $_POST['price1']!=null AND $_POST['price2']!=null){
      $price1=$_POST['price1'];
        $price2=$_POST['price2'];
        if ($rents->location==$_POST['location'] && $price1 < $price2) {
            $foralert=1;
        }
            elseif($rents->location==$_POST['location'] AND $price>=$price2 && $price <=$price1 ){
              $price=$rents->price;
        ?>
      <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
             <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
      <?php }}elseif($_POST['type']!=null AND $_POST['location']==null AND $_POST['price1']!=null AND $_POST['price2']!=null){
        $price1=$_POST['price1'];
        $price2=$_POST['price2'];
        if ($rents->type_name==$_POST['type'] && $price1 < $price2) {
            $foralert=1;
        }
           elseif($rents->type_name==$_POST['type'] AND $price>=$price2 && $price <=$price1){
            $price=$rents->price;
        ?>
       <tr>
            <td>
                <?= $rents->type_name ?>
           </td>
           <td>
               <?php  echo number_format("$price");?> 
           </td>
           <td>
                <?= $rents->location ?>
           </td>
           <td>
                <?= $rents->contact_phnumber ?>
           </td>
           <td>
                <?= $rents->contact_address ?>
           </td>
           <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
     <?php } 
     }}else { 
      $price=$rents->price;
      ?>
        <tr>
          <td>
              <?= $rents->type_name ?>
         </td>
         <td>
             <?php  echo number_format("$price");?> 
         </td>
         <td>
              <?= $rents->location ?>
         </td>
         <td>
              <?= $rents->contact_phnumber ?>
         </td>
         <td>
              <?= $rents->contact_address ?>
         </td>
         <td>
          <a href="<?= $this->url('mainpage', ['action' => 'detail', 'id' => $rents->id]) ?>" class="btn btn-default btn-enquiry col1 submit-btn clicktrack"  >View Detail</a>
        </td>
      </tr>
 <?php        }
endforeach; 
?>
     </table>
   </div>
   <?php 
   if($foralert=="1"){?>
    <script type="text/javascript">
    alert("Maximun Price can't greater than Minimun Price!!");
    </script>
   <?php } ?>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> 
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="../public/js/paging.js"></script> 
<script type="text/javascript">
            $(document).ready(function() {
                $('#tableData').paging({limit:5});
            });
        </script>
        <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script type="text/javascript">
            $(document).ready(function() {
                $('#tableData2').paging({limit:5});
            });
        </script>
        <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script>
    function get(obj) {
      return document.getElementById(obj);
    }
    function switchOne() {
      get("tab-1").style.background="#DEF0F7";
        get("tab-2").style.background="#1FEFE5";
        get("panel-1").style.display="block";
        get("panel-2").style.display="none";
    }
    function switchTwo() {
      get("tab-1").style.background="#1FEFE5";
      get("tab-2").style.background="#DEF0F7";
      get("panel-1").style.display="none";
      get("panel-2").style.display="block";
    }
    </script>

    <?php if (isset($_POST['search2'])) { ?>
      <script type="text/javascript">
    $(document).ready(function(){

          switchTwo();
          });
          </script>
    <?php } ?>
</body>
</html>